### ISSUE TITLE
Type tag hints do not show when tab forces scrolling

### ISSUE THREAD

**Issue by thefallofbecause** [Wikunia/brackets-FuncDocr#11]
Not exactly a bug, this falls more into the category of unexpected behaviour.

If you hit Tab to jump to the Type tag on a line that is partially or completely rendered off-screen (thus forcing the document to scroll) the Type hints do not show. This occurs whether there are open panes below the document or whether all panes are closed.

Unsure if there is anything that can be done about this, based on a quick glance at the code I assume this is an issue in Brackets itself.

**Comment by qyouqme** [comment]
I have the same issue.Codes hints never popup.I love your tool,but I love other tools too.Would you please solve this bug?

**Comment by Wikunia** [comment]
Unfortunately I have no idea why this happens :/ But I will have a look at the weekend again.

**Comment by Wikunia** [comment]
One way would be to have the current selection always in the center of the editor that works but don't know if you like it @thefallofbecause @qyouqme
