### ISSUE TITLE
Shortcut doesn't work on OS X, can't set shortcut either

### ISSUE THREAD

**Issue by Richard-A** [Wikunia/brackets-FuncDocr#21]
Ctrl-Alt-D doesn't work on a OS X (Tested with OS X 10.7.5), I can't set it to Command-Alt-D either.

**Comment by Wikunia** [comment]
Do you have errors in the debug log? (F12, Debug->Show Developer Tools)

**Comment by Wikunia** [comment]
@Richard-A any news?

**Comment by apla** [comment]
just fixed it #30
