### ISSUE TITLE
PhpDoc should be @return, not @returns

### ISSUE THREAD

**Issue by Richard-A** [Wikunia/brackets-FuncDocr#22]
When creating the docs for a PHP function or method, the docs will say something like this:

    /**
     * [[Description]]
     *
     * @returns String [[Description]]
     */
    function foo()
    {
        return "Bar";
    }

The @returns part should be @return (Linking of user is not intended).

On a note, it should be *string*, not *String*

**Comment by Wikunia** [comment]
Hi @Richard-A,

where did you look up the "spelling" of the datatypes? I always find the uppercase version.

**Comment by Richard-A** [comment]
From the php docs:

>PHP supports eight primitive types.
>
>Four scalar types:
>
> - boolean
> - integer
> - float (floating-point number, aka double)
> - string

All primitive types are lower case.
http://php.net/manual/en/language.types.string.php

**Comment by Wikunia** [comment]
Ah okay thanks @Richard-A I will push a new version later this day. Stay tuned!

**Comment by cbaldwinweb** [comment]
Data types are usually always recognized as first letter capital when commenting. All other methods such as keywords as lowercase but especially in js `new String` not `string ` that is there correct method in my eyes and I'll always use it.
