### ISSUE TITLE
Conflict with other language syntax hint extensions?

### ISSUE THREAD

**Issue by qyouqme** [Wikunia/brackets-FuncDocr#23]
Hi man,your extension works fine.But my other language syntax hint extensions all stop.eg:brackets-wp-functions-hint,brackets-php-syntax-hint.I want to work with them together...
I tested,without your extension,they work fine.

**Comment by Wikunia** [comment]
Can you send me your debug log?
I'll have some errors with `brackets-php-syntax-hint` but I could resolve them inside `brackets-php-syntax-hint` and not inside `FuncDocr`

**Comment by qyouqme** [comment]
Ok tomorrow send to you. It's midnight now. I have on bed. Thank you for reply.



发自我的小米手机

Ole Kröger <notifications@github.com>编写：

**Comment by Wikunia** [comment]
你好！
When does this happen? So after using special keys or after using FuncDocr ones or...

**Comment by qyouqme** [comment]
Just open Brackets,this happen.With FuncDocr ,have these errors.Without FuncDocr,have less errors.

**Comment by Wikunia** [comment]
谢谢！
one more question: you wrote the extensions doesn't work so you mean they have no function at all or are there only some functions that doesn't work?
我今天看！(or how would you say: I will have a look later today? Just started learing Chinese 2 month ago ;) )

**Comment by qyouqme** [comment]
Your extension is useful.It can work fine alone.It just can't work with some other extensions together.Good work,man!

" I will have a look later today?" in Chinese is "我今天晚些时候会看一下？".

**Comment by Wikunia** [comment]
Way to long (Chinese) :D 
I resolved the problem inside the brackets wp hint extension and it's the same in the brackets php syntax hint extension which unfortunately has no repository but you can change the same thing or I can send you the changed code :)

Have a nice day!

**Comment by qyouqme** [comment]
I just know a little html,css,js and php.So please send the changed code to me.Thank you very much.

**Comment by Wikunia** [comment]
You have a new mail!
