### ISSUE TITLE
Show "Annotate" option in Edit menu

### ISSUE THREAD

**Issue by mitchhentges** [Wikunia/brackets-FuncDocr#24]
I couldn't tell how to annotate until I looked at the Github page. This extension could be made even easier to use if there was a option in the Edit menu with the shortcut key shown.

Mockup:
![menuoption](https://cloud.githubusercontent.com/assets/7784737/5728787/0f183ca8-9b22-11e4-8e46-81ac4761c470.png)

**Comment by Wikunia** [comment]
Hi @mitchhentges,
thanks, at the moment there is only a `FuncDocr Settings` entry in the File menu where you can change the shortcut but I will try to implement this as well.
