### ISSUE TITLE
Move "FuncDocr Settings" to View menu

### ISSUE THREAD

**Issue by mitchhentges** [Wikunia/brackets-FuncDocr#25]
"FuncDocr Settings" somewhat works, in a UX sense, when in the "File" menu. However, it decreases usability, as some users assume that the exit button will be at the bottom of the File menu.

When clicking at the bottom menu entry opens up a settings dialog instead of closing the program, a bad experience is created.

Meanwhile, if the FuncDocr Settings was:
- Further up the "Files" menu list, or
- In the View menu list
usability would be increased.

**Comment by Wikunia** [comment]
My current File menu looks like this:
![brackets-funcdocr-menu](https://cloud.githubusercontent.com/assets/4931746/5728932/91d83df4-9b6e-11e4-9597-6492d122a7b0.png)
But actually your text makes sense so I will have a look how to change it :)

**Comment by mitchhentges** [comment]
As an aside, this extension is great :)
Thanks for the great tool!

**Comment by Wikunia** [comment]
You're welcome :)
