### ISSUE TITLE
Assume [param=true] more often

### ISSUE THREAD

**Issue by mitchhentges** [Wikunia/brackets-FuncDocr#26]
When a parameter is set to
```
function doing(param) {
    param = (typeof param !== 'undefined') ? param : true;
}
```
FuncDocr recognizes it as a default parameter and enters 
`@param   {Boolean}   [param=true]`
accordingly.

However, when I do the following (which is shorter)
```
function doing(param) {
    param = (typeof param === 'undefined') || param;
}
```
FuncDocr just puts out:
`@param   {[[Type]]} noSelection`

__TL;DR__ Recognize `param = (typeof param === 'undefined') || param;` as a default boolean parameter

**Comment by Wikunia** [comment]
I will add your method as well, didn't know that one :D
