### ISSUE TITLE
Setting for auto indent

### ISSUE THREAD

**Issue by ficristo** [Wikunia/brackets-FuncDocr#27]
I would like to have a setting to disable the auto indent.

**Comment by Wikunia** [comment]
I'll work on that at the weekend!

**Comment by Wikunia** [comment]
I hope you meant this autoindent feature. It should work now :)
Maybe you would like to check it and just say whether it works.

**Comment by ficristo** [comment]
I tried a bit the new version: but if I see the new setting, it doesn't seems to work.
To clarify: when I press the tab button to move between the various tag [[Description]], {[[Type]]} to update them, I don't want the text to be vertically aligned.

**Comment by Wikunia** [comment]
Oh I thought about the enter function which indents when you have a multi line description for params or returns. 
Is there an error with indentation or do you simply don't like indentation?

**Comment by Wikunia** [comment]
Oh I thought about the enter function which indents when you have a multi line description for params or returns. 
Is there an error with indentation or do you simply don't like indentation?

**Comment by ficristo** [comment]
I like the indentation per se, but most files I work with do not have the doc comments aligned and for the moment I don't want to change them.

**Comment by Wikunia** [comment]
Well the question is whether anyone else profits from the setting. You can indent a function automatically using the shortcut but maybe you have a lot of functions... The question is it worth it to add a setting for disabling indentation or a button to autoindent all functions?

**Comment by Wikunia** [comment]
Maybe you would like to check the new version ;) `Install from Url`

**Comment by ficristo** [comment]
Thanks for both features!
