### ISSUE TITLE
Use callback for the types

### ISSUE THREAD

**Issue by ficristo** [Wikunia/brackets-FuncDocr#28]
If I have defined a @callback comment I would like to have it too in the list of the types.

**Comment by Wikunia** [comment]
@ficristo do you want to have a `callback` as a parameter type? So sth like
```
/**
* abcdef
* @param {callback} callback callback function
*/
```

**Comment by ficristo** [comment]
Let's say I have a doc comment in the file for my callback type as follow:
``` javascript
/**
 * @callback MyObj~myCb - blah blah ...
 * @param ...
 */
```
It would be nice that when I go to change the types 
``` javascript
 * @param {[[Type]]}
```
the plugin will give me the option MyObj~myCb too. So in the list I'll see:
Number,
String,
...
Function,
MyObj~myCb

**Comment by Wikunia** [comment]
ah okay you would like to have the callback function as a type. Sounds interesting :) Never thought about it, but I think it can improve the documentation so I will have a look!

**Comment by Wikunia** [comment]
@ficristo it would be nice when you can download the newest version (v0.8.4 from Url) and test it! 
Have a nice weekend!
