### ISSUE TITLE
Error "Cannot assign..." in Brackets console

### ISSUE THREAD

**Issue by mitorez** [Wikunia/brackets-FuncDocr#29]
I'm seeing the following error in my Brackets console: "Cannot assign Ctrl-Alt-D to funcdocr. It is already assigned to funcdocr"

Windows 7 Enterprise SP1 64-bit
Brackets Release 1.1 build 1.1.0-15558
FuncDoor 0.8.2

**Comment by Wikunia** [comment]
I have this issue as well but don't know why this "error" occurs. I'll try to check it at the weekend!

**Comment by Wikunia** [comment]
You can download it using `Install from Url`. There will be an update at the weekend with an option for #27

**Comment by mitorez** [comment]
Thanks for the quick turnaround - issue resolved :)
