### ISSUE TITLE
not working for some files

### ISSUE THREAD

**Issue by apla** [Wikunia/brackets-FuncDocr#31]
sometimes getFunctionCodeTypes returns `false` at `main.js:225`:

``` javascript
var codeTypes = getFunctionCodeTypes(editor,position,signature.parameters);
```

then, `false.code === undefined` at `main.js:235`: 

``` javascript
signature.parameters = checkParamsOptional(codeTypes.code,signature.parameters);
```

`undefined.substr` => `Uncaught TypeError: Cannot read property 'substr' of undefined` at `main.js:1204`: 

``` javascript
code = code.substr(code.indexOf('{')+1);
```

**Comment by Wikunia** [comment]
I hope this one works!
Can you send me snippets of the functions where codeTypes doesn't work? Thanks for the issue!

**Comment by apla** [comment]
seems works with this patch. you can check my gist:

https://gist.github.com/apla/9423c173c97c3c350690

**Comment by Wikunia** [comment]
Thanks again there was a bug with two single line comments back-to-back cause I used a `2` instead of an `1` :D
