### ISSUE TITLE
FuncDocr preferences always show up at Brackets startup

### ISSUE THREAD

**Issue by glepretre** [Wikunia/brackets-FuncDocr#32]
Hi,

I have recently installed your plugin and noticed a strange behavior:

The FuncDocr preferences modal always pop-up when I launch Brackets. Am I the only one?

I'm running Brackets latest stable (build 1.1.0-15558) on Linux Mint Debian Edition. I had this behavior since FuncDocr v0.8.3 and still have it with v0.8.4.

Please tell me if you need more info about to reproduce it or if I can help finding its cause. :smiley:

**Comment by Wikunia** [comment]
I am pretty sure that one extension uses the same Shortcut (`Ctrl-Alt-D`) so you need to change it in the settings menu. Sorry for the strange behaviour. I should definitely change the menu... Adding a text and maybe allow a no shortcut option. Thanks for the issue!

**Comment by glepretre** [comment]
Thanks for the quick reply!

I'm using [Brackets keyremapper](https://bitbucket.org/sacah/brackets-key-remapper) to manage my shortcuts and I don't see any conflict in my `brackets.json` preferences file (all assigned shortcuts, custom or not, are printed there).

However, I disabled the FuncDocr `Ctrl-Alt-D` and it fixes the issue. 

I have a gnome keybinding on `Ctrl-Alt-D` but I don't see how it would conflict without pressing it?! :confused: 

You should not change your code if I'm the only one to experience this bug :wink:

**Comment by Wikunia** [comment]
Can you check the DevTools (F12)? Are there any bugs? And the key binding should be here https://github.com/Wikunia/brackets-FuncDocr/blob/master/main.js#L1505 Maybe you can debug a bit, so look what's inside existingKeybindings

**Comment by glepretre** [comment]
Nothing relevant in the DevTools...

![selection_002](https://cloud.githubusercontent.com/assets/5930831/5898449/e0f031a4-a54f-11e4-8e0c-68d2964daf47.png)

**Comment by Wikunia** [comment]
And the settings menu appears? That is strange because I check if `Ctrl-Alt-D` is inside the existingKeyBindings and it looks like it's inside it but it shouldn't... give me a second! I have an idea which is strange but maybe helps :)

**Comment by glepretre** [comment]
Disabling the keyremapper extension also fixes the bug.

Here's what I have in `brackets.json`:

    "funcdocr.shortcut": "Ctrl-Alt-D",
    "funcdocr.shortcutMac": "Ctrl-Alt-D",
    "funcdocr.autoindent_enter": true,
    "funcdocr.autoindent_tab": true,
    "sacah.keyremapper.loadremapperdialog.keymap": {
        "funcdocr": {
            "commandID": "funcdocr",
            "key": "Ctrl-Alt-D"
        }
    //...
    }

**Comment by Wikunia** [comment]
Can you try install from Url? Hope that one helps (kind of untested :D )

**Comment by glepretre** [comment]
Sure! Which URL should I paste? :smile: 

(If it doesn't work, I will apply the same diff :wink: to test it)

**Comment by Wikunia** [comment]
It's inside the `master` branch because different branches aren't supoorted by `Install from Url` , I believe. => https://github.com/Wikunia/brackets-FuncDocr
Thanks!

**Comment by glepretre** [comment]
Installing from URL works perfectly!

Your commit seems to fix the bug.

I no longer have these two lines in `brackets.json`:

     "funcdocr.shortcut": "Ctrl-Alt-D",
     "funcdocr.shortcutMac": "Ctrl-Alt-D",

**Comment by Wikunia** [comment]
![brackets-funcdocr- 32](https://cloud.githubusercontent.com/assets/4931746/5898885/653a9356-a554-11e4-9cbc-13f8a04830e5.png)
Do you have this in your edit menu? And the shortcut works normally?

**Comment by glepretre** [comment]
No, I don't have the 'annotate' menu item. 
And the shortcut doesn't seem to work... :disappointed:

**Comment by Wikunia** [comment]
Okay I understand that you don't have a menu item but I hoped that the shortcut works based on your other extension... Can you try this test as well? :)

**Comment by glepretre** [comment]
Oh sorry, I thought it was the sortcut to open the FuncDocr !! Yes, it works to annotate functions.

**Comment by Wikunia** [comment]
Okay, does the second test works with showing the MenuItem in the Edit menu?

**Comment by glepretre** [comment]
Yes, I do have it!

**Comment by Wikunia** [comment]
Sound like everything works now :)
Thanks for the issue and have fun with FUNcDocr :)
