### ISSUE TITLE
add support for es6 classes

### ISSUE THREAD

**Issue by zaggino** [Wikunia/brackets-FuncDocr#33]
i'm working with es6 and classes look like this:
```
class TodoStore extends EventEmitter {
  
  constructor() {
    this._todos = {};
  }
  
  create(text) {
    var id = Date.now();
    this._todos[id] = {
      id,
      complete: false,
      text
    };
  }
  
  destroy(id) {
    delete this._todos[id];
  }
  
}
```
would it be possible to get a support for these? thanks
link: https://babeljs.io/docs/learn-es6/#classes

**Comment by Wikunia** [comment]
So you would like to have sth. like this:
```
class SkinnedMesh extends THREE.Mesh {
  /**
   * [[Description]]
   * @param {[[Type]]} geometry  [[Description]]
   * @param {[[Type]]} materials [[Description]]
   */
  constructor(geometry, materials) {
    super(geometry, materials);

    this.idMatrix = SkinnedMesh.defaultMatrix();
    this.bones = [];
    this.boneMatrices = [];
    //...
  }
  update(camera) {
    //...
    super.update();
  }
  static defaultMatrix() {
    return new THREE.Matrix4();
  }
}
``` 
right?
I have to think about how to check whether the next line is a function declaration without the word `function`. But well JS/ECMAscript never uses sth like `string (...) {` anywhere else, right?

**Comment by zaggino** [comment]
That's right, I think you can safely check for `string (...) {`

**Comment by Wikunia** [comment]
You can download the newest version from url. the `[[Link]]` type doesn't work for ES 6 at the moment cause I use a brackets function to get all functions in the current document and that doesn't support ES 6 at the moment. But I think that feature isn't sooo important.

**Comment by zaggino** [comment]
Thanks, works for me ;) I'll let you know if I'll encounter any more problems.
