### ISSUE TITLE
ui to change default.json

### ISSUE THREAD

**Issue by tushariscoolster** [Wikunia/brackets-FuncDocr#34]
want ui to change default properties

**Comment by Wikunia** [comment]
Do you think that it's important? Do you have to change these things often?

**Comment by tushariscoolster** [comment]
Not often...but that's a core of your plugin which should be customisable

**Comment by Wikunia** [comment]
I don't think that it's a core :D but yeah I think about it.
Thanks for the feature request ;)

**Comment by tushariscoolster** [comment]
Thanks man

**Comment by Wikunia** [comment]
Reopened it as a reminder :)

**Comment by Wikunia** [comment]
Unfortunately I don't have much time and I don't know which is the best idea to implement this into a UI. Do you have an idea? You want to change things like 
```
{
    "tags": {
		"createDate": "@createDate [[Date]]",
		"lastmodifiedBy": "@lastmodifiedBy [[Name]]", 
		"lastmodifiedDate":"@lastmodifiedDate [[Date]]",
        "link": "{@link [[Link]] [[Description]]}",
        "param": "@param {[[Type]]} [[Description]]",
        "returns": "@returns {[[Type]]} [[Description]]"
    },
	"types": {
			"number": 	"Number",
			"string": 	"String",
			"boolean":	"Boolean",
			"array": 	"Array",
			"object": 	"Object",
			"regexp": 	"RegExp",
			"function": "Function"
	}
}
``` right?

**Comment by tushariscoolster** [comment]
I realized default json change not needed
