### ISSUE TITLE
Cannot get it to make the doc neither with shortcut nor natural way

### ISSUE THREAD

**Issue by frsechet** [Wikunia/brackets-FuncDocr#35]
Hi,

I just installed the extension (Version 1.1.0-15558 on Mac/Yosemite), but cannot get it to work on any file, any function (php of course though), no matter whether it's a method in a class or just a plain function.

Neither "/** + Enter" nor the shortcut (I tried to replace it with another custom one since the original couldn't work) will work. The shortcut doesn't do anything and "/** + Enter" simply writes /** + new line...

Am I doing it wrong, or is there a bug somewhere? What can I send you to help you fix this?

Thanks!

**Comment by Wikunia** [comment]
Hi,

can you send me your php file (a part of it)? 
And are there any los in the dev tools? (F12 in Brackets)

Thanks!

**Comment by Wikunia** [comment]
That was hopefully the bug ;) 
Maybe you would like to install this version from URL and then I can register it.
Thanks for the issue!

**Comment by frsechet** [comment]
Yep, that fixed it for regular functions! Didn't work for methods though, but I'm not sure this extension is supposed to work on methods?

**Comment by Wikunia** [comment]
Can you send me an example? You mean simple functions/methods inside a class?

**Comment by frsechet** [comment]
Stuff like that for example (Laravel generic file):

<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class PagesController extends Controller {

	public function about()
	{
		return view('pages.about');
	}
	
	public function contact()
	{
		return view('pages.contact');
	}
	
}

**Comment by Wikunia** [comment]
Hope that one helps :)

**Comment by frsechet** [comment]
Fantastic! Thanks a lot :-)
