### ISSUE TITLE
Creating new documentation doesn't work on 0.8.8

### ISSUE THREAD

**Issue by OttoRobba** [Wikunia/brackets-FuncDocr#36]
Typing in /** and hitting enter or using the shortcut Ctrl+Alt+D no longer creates the jsdoc block.

1. Create a function

    var stuff = function(string) {};

2. Write /** on the line above it
3. Hit enter

**Comment by Wikunia** [comment]
Thanks for the issue. I forgot this way of generating a function, it worked some day cause my regex was a bit more flexible than now. I will implement this soon. Stay tuned!

**Comment by angeldevz** [comment]
still not working and my plugin is updated (0.8.9) :(

**Comment by Wikunia** [comment]
For the same type of function? :/

**Comment by angeldevz** [comment]
Ahh.. sorry, no.. 

With this kind of function
`Stuff.getThingsDone = function() {}`

It was working before on that kind of function.

**Comment by Wikunia** [comment]
Can you try using `Install from Url`? Sorry again!

**Comment by angeldevz** [comment]
Cool! Working now! Thanks!  :+1: :smile:

**Comment by Wikunia** [comment]
Thanks for the issue!
