### ISSUE TITLE
FuncDocr doesn't work if the function is inside an object collection

### ISSUE THREAD

**Issue by fmaida** [Wikunia/brackets-FuncDocr#37]
Thanks for your wonderful extension. I'm using FuncDocr 0.8.10 on Brackets 1.2 under Mac OS X 10.10.2
To make an example, If I write this piece of code:

```
var person = {
        
    name: "John",
    
    sayName: function(foo, bar) {
        console.log("Hi, my name is " + this.name + " and I also do " + foo + bar);
        // do some other things...
    }
}
```

When I try to document the function sayName it doesn't work. I put the cursor over "sayName: function(foo, bar)" and I write "/**" and press enter but nothing happens.

Thank you again and best regards

**Comment by Wikunia** [comment]
Ah shit I shouldn't have change the regex. :D thanks for your issue. I will implement this soon :)
Stay tuned!

**Comment by fmaida** [comment]
Thank you very much :-)

**Comment by Wikunia** [comment]
Can you please install the new version from Url first? And say if everything works as expected?
Thanks!

**Comment by fmaida** [comment]
Thanks. I downloaded and tried the zipped master and now it's working properly; I didn't had enough time to test it extensively but so far it has worked in each test I made.
