### ISSUE TITLE
Function prototypes

### ISSUE THREAD

**Issue by dapullar** [Wikunia/brackets-FuncDocr#38]
Is it possible to add the ability to use FuncDocr with object prototype functions? Currently will either duplicate the line above, or no action is performed. 

Example:
```js
Example.prototype._parseData = function (data, params) {
    // etc
};
```

Another common case that doesn't work is when you are declaring functions preceding with `this`.

Example:
```js
this.ExampleException = function(message) {
    this.name = "ExampleException";
    this.message = message;
}
```

**Comment by Wikunia** [comment]
Hi,

can you please try version 0.8.12 (Install from Url)
Thanks for the issue! Have a nice day.

**Comment by dapullar** [comment]
Ahh, beauty, works like a charm, thanks you

**Comment by Wikunia** [comment]
You're welcome. At the moment I can't register the newest version using https://brackets-registry.aboutweb.com (cause I'm getting a bad request feedback :( ) I will try it again in some hours.
