### ISSUE TITLE
Freezing Brackets

### ISSUE THREAD

**Issue by cbaldwinweb** [Wikunia/brackets-FuncDocr#39]
When I try writing `/**` then pressing enter the entire Brackets freezes I have to end the task. What is up with that issue guys?

**Comment by Wikunia** [comment]
Hey,
I am sorry :/ is the file big or do you have the problem with every file?

**Comment by cbaldwinweb** [comment]
Every single file. Even just a starter file to try this out it does it. Very strange and I like the easy inline documentation.

**Comment by Wikunia** [comment]
Can you please follow these steps to find the cause of that problem.
1. Open the extension folder (`Help->Show Extensions Folder`) 
2. `Ctrl-X` every extension (not FuncDocr) inside user into disabled
3. Reload brackets
4. Try it again

Thanks!

**Comment by Wikunia** [comment]
Anything new? Maybe you have some debug logs.

**Comment by cbaldwinweb** [comment]
I will try this now I've been away for a while now.

**Comment by cbaldwinweb** [comment]
It works now, I deleted Themes for Brackets and Quotes or something like that. Anyways it's working, anyways, I'll add the mixed data types to my forked version and push it again.

**Comment by Wikunia** [comment]
Can you specify the extension exactly? And does the extension in=tself causes the problem or only in combination with FuncDocr?

**Comment by cbaldwinweb** [comment]
Yes I will try to pinpoint the exact conflict Wikunia

**Comment by cbaldwinweb** [comment]
It's either of these two

https://github.com/chuyik/brackets-snippets

or 

https://github.com/caseyg1204/brackets-quoter

Not 100% sure because now that FuncDocr was loaded first it's not giving a problem. No freezing, I'll try and find the freezing issue again, hard to replicate it.
