### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by zaggino** [Wikunia/brackets-FuncDocr#45]
version: 0.8.13
at /Users/zaggino/Library/Application%20Support/Brackets/extensions/user/funcdocr/main.js:793

![image](https://cloud.githubusercontent.com/assets/1067319/6813824/eb3c4eae-d2cc-11e4-8929-b843b6542d15.png)

**Comment by Wikunia** [comment]
Looks like a bug cause of the unknown language...
Can you send me the part of the file where this error appears and the file extension?

**Comment by zaggino** [comment]
I have no idea which file I had open, doesn't the extension work for only certain languages?

**Comment by Wikunia** [comment]
Can you please install from URL and try it again? Thanks for the issue. I hope it works now ;)
