### ISSUE TITLE
FuncDocr doesn't work if the function is inside an object collection

### ISSUE THREAD

**Issue by vazyvite** [Wikunia/brackets-FuncDocr#46]
Hi
I reopen the issue #37 for the new version 0.8.13.

The documentation isn't generated after /** + Enter.
But if the documentation is already generated, FuncDocr works.

**Comment by Wikunia** [comment]
Sorry @vazyvite,
i've changed some regex stuff which was maybe not the best idea. I will have a look later today. Stay tuned and thanks for the issue!

**Comment by Wikunia** [comment]
I've tested it and it works with the example given by #37 
Are there any errors in the console?

**Comment by vazyvite** [comment]
Sorry, it's not the same issue as #37...

I declared some functions by this way :
var test = function (chose) {
	// instructions
},
truc = function (hop) {
	// instructions
};

FuncDocr works well for the first function but not for the followings : 
/**
 * [[Description]]
 * @param {[[Type]]} chose [[Description]]
 */
var test = function (chose) {
	// instructions
},
/**
truc = function (hop) {
	// instructions
};

**Comment by pbojan** [comment]
What about functions in classes with namespaces? It seems it doesn't work currently.

**Example:**
```javascript
namespace.namespace1.class.prototype.method = function(param1, param2) {};
```

**Comment by Wikunia** [comment]
@pbojan can you try this version, please :) (Install from URL)
