### ISSUE TITLE
Functions get squished if there are multiline comments in between.

### ISSUE THREAD

**Issue by Hirse** [Wikunia/brackets-FuncDocr#47]
I have copied some function from another (poorly documented) source and had code that looked like this:
```js
/**
 * This is function a
 * @param   {Number}  b this is b
 * @returns {Boolean} always false
 */
var a = function (b) {
    return false;
};

/*
 * Any Block comment
 */
var c = function (d) {
    return false;
};
```
When I now use the `Ctrl`+`Alt`+`D` hotkey to add / reformat the JsDoc for function c, the first function and the multiline comment are simply deleted and the extension behaves like the first JsDoc belongs to the second function:
```js
/**
 * This is function a
 * @param   {[[Type]]} d [[Description]]
 * @returns {Boolean}  always false
 */
var c = function (d) {
    return false;
};
```

**Comment by Wikunia** [comment]
Ah it's because the second docblock starts with `/*` instead of `/**`.
Thanks for the issue I will have a deeper look!

**Comment by Wikunia** [comment]
A deep look later :D Can you install from URL please and test this version. Hope there are no bugs now!

**Comment by Hirse** [comment]
Yes, works fine.
Thanks for the quick fix.

**Comment by Wikunia** [comment]
Well thanks for the issue :)
