### ISSUE TITLE
Reformat JsDoc in one operation

### ISSUE THREAD

**Issue by Hirse** [Wikunia/brackets-FuncDocr#48]
When I add a JsDoc on a function that has already a malformed or incomplete documentation, the existing one is transformed into the new format. This looks to be one step.
But when I decide to revert that change and use undo, I have to undo twice, because there are two steps pushed on the undo stack:
 1. Remove all comments
 2. Add the new JsDoc (containing the old parts)

I think it would be more intuitive to have this in one batch.

**Comment by Wikunia** [comment]
I am using brackets functions for it and I am not sure if it's easily or even possible but I'll have a look later! Have to work on another Brackets extension that I want to release :D

**Comment by Hirse** [comment]
In the Brackets API there is `[batchOperation](http://brackets.io/docs/current/modules/document/Document.html#Document-batchOperation)`.
Maybe that could work for you.

**Comment by Wikunia** [comment]
There is always something new :) Thanks!

**Comment by Wikunia** [comment]
Try it out! Again `Install from Url` :)
