### ISSUE TITLE
No support for jsx files

### ISSUE THREAD

**Issue by brazenskies** [Wikunia/brackets-FuncDocr#49]
Hi,

With React becoming more and more popular it would be great if you could add support for jsx files. This is a very useful plugin, but unfortunately I can't use it due to this reason

**Comment by Wikunia** [comment]
Can you send me some example files and functions? 
And do you want to have special things in it? There are special things like `this.props` inside ReactJS and I am supporting in in React javascript files but don't know where jsx is different.

**Comment by brazenskies** [comment]
Thanks for the quick response.

Here are steps to recreate the issue I was experiencing...

1.  Open a .js file in Brackets
2.  Create a function
3.  Above that function type '/** + Enter'
4.  Note that the FuncDocr extension kicks in and I can create docs
5.  Now open a react .jsx file
6.  Create a function
7.  Above that function type '/** + Enter'

Expected outcome:  I'd expect the extension to kick in like it did within the .js file
Actual outcome:  The extension did not work and I simply ended up with a new line

There's nothing else React specific that is required from this extension, just that it performs inside a .jsx files as it does within a .js file.

Thanks again,
Greg

**Comment by Wikunia** [comment]
Can you install the newest version from Url? And test it? Thanks for the issue!

**Comment by brazenskies** [comment]
Perfect, thanks for the quick fix, should make my life much easier now :)

**Comment by Wikunia** [comment]
If you like to have any special react features just say a word ;)

**Comment by brazenskies** [comment]
will do, thanks.

(you left in a console log :))

**Comment by Wikunia** [comment]
Shit just registered the new version

**Comment by glepretre** [comment]
@Wikunia Should we apply the update or there is a problem with it?

**Comment by Wikunia** [comment]
I've registered the new version without console log v0.8.18 it should work or do you have a problem with that version?

**Comment by glepretre** [comment]
@Wikunia No, I have not updated yet :smiley: I have seen your comment (received by mail) so I just came here to ask if we should wait before applying the update (in case of unwanted breaking change) :wink:.
