### ISSUE TITLE
New line not recognised from header 

### ISSUE THREAD

**Issue by sandcastle** [Wikunia/brackets-FuncDocr#50]
When pressing enter from the header it does not recognise it as a new line and automatically create a `*` for the line.

Before (cursor is at the end of the comment header):

![cursor_on_header](https://cloud.githubusercontent.com/assets/668657/6992400/5774831e-dafe-11e4-8dcd-b34d183c7ab9.png)

After (enter is pressed):

![bad_line](https://cloud.githubusercontent.com/assets/668657/6992404/9d52d994-dafe-11e4-8bd1-7105d5b4704b.png)

**Comment by Wikunia** [comment]
Thanks for the issue! Can you try this one please (Install from URL) Happy Easter

**Comment by sandcastle** [comment]
Thanks, that did the trick :smiley:
