### ISSUE TITLE
Preferences for FuncDocr always showing

### ISSUE THREAD

**Issue by IamAdamJowett** [Wikunia/brackets-FuncDocr#51]
Love the extension except the Preferences modal is showing each and every time I start up brackets which is starting to get a little annoying. It seems to save the preferences to the preference file ok, so not sure why it shows on startup each time.

![image](https://cloud.githubusercontent.com/assets/294948/7124680/4fef13e4-e26e-11e4-9eec-8ed3c3cbfa33.png)

**Comment by IamAdamJowett** [comment]
Ok after looking through the code, I can see it is showing due to there being a conflict with the keyboard shortcut with another extension (Grunt for Brackets) which also tries to use Ctrl-Alt-D. Makes sense to show it, but perhaps it needs specific modal messaging to let the user know why it is showing in this case.

**Comment by Wikunia** [comment]
Ah okay and thanks for the idea!

**Comment by Wikunia** [comment]
![brackets-funcdocr-menu-reminder 51](https://cloud.githubusercontent.com/assets/4931746/7422407/f2c5376c-ef8c-11e4-8f15-22db7bf10fdd.png)
I am so sorry! I've kind of forgotten this issue. Do you thing this message would be okay? I know it isn't the best (I am definitely not a designer :D) but I hope it's "okay" ;) Have a nice weekend @IamAdamJowett

**Comment by IamAdamJowett** [comment]
All good @Wikunia thanks for all the work. A simple "This shortcut is already in use, please choose another" will do the trick for sure.
