### ISSUE TITLE
ES6 class/method support

### ISSUE THREAD

**Issue by ndugger** [Wikunia/brackets-FuncDocr#52]
It would be fantastic to have ES6 support for class method delcarations;

    class Foo {
        /** jsdocs here... */
        bar() {

        }
    }

**Comment by Wikunia** [comment]
Hi,

a function is some text the parameter brackets and the curly one or what is the best way to check whether the next line contains a function definition? I will try to implement it as soon as possible ;)

Have a nice day and thanks for the issue!

**Comment by Wikunia** [comment]
I ask because it should actually work already. 
The given example has no parameters so if you want to comment this appears:
```
class Foo {
 
    /**
     * [[Description]]
     */
    bar() {

    }
}
```
Maybe there is another bug? Do you have any console logs?
