### ISSUE TITLE
PHP array()

### ISSUE THREAD

**Issue by cristidraghici** [Wikunia/brackets-FuncDocr#53]
The following line does not generate anything

```
public static function fname($var1, $var2=array())
```
until changed to:

```
public static function fname($var1, $var2=array)
```
which is not valid php syntax.

**Comment by Wikunia** [comment]
Can you please install via url and test v0.8.21? Thanks in advance

**Comment by cristidraghici** [comment]
Thank you for the quick reply. I have just tested it and works correctly. Thanks again!

**Comment by Wikunia** [comment]
I'll make some more tests today and tomorrow and will register the new version afterwards.
