### ISSUE TITLE
Function with default parameters (PHP)

### ISSUE THREAD

**Issue by adricorse** [Wikunia/brackets-FuncDocr#54]
Hello,
try to add a default parameters in your function, I have this resullt : 

```php
    /**
     * [[Description]]
     * @param  [[Type]] [$config=""] [[Description]]
     * @return [[Type]] [[Description]]
     */
    protected function demo($config=""){

```
So, if I change Type or Description in phpdoc  for this variable and I use shortcut to add phpdoc in this method, my  changes are removed.
This bug appear only with default parameters.

**Comment by Wikunia** [comment]
Can you show me the code snippet before and after the bug? I can't reconstruct this bug. Thanks!

**Comment by adricorse** [comment]
I have Ubuntu 15.04and all update, the latest version of Brackets, to reconstruct this bug, check this example : 
```php
<?php
public class Example{
    protected function demo($abc = ""){
    }
}
?>
```
Now, use the shortcut to make a phpdoc for this function (Linux : CTRL + ALT + D)
```php
<?php
public class Example{
    /**
     * [[Description]]
     * @param [[Type]] [$abc = ""] [[Description]]
     */
    protected function demo($abc = ""){
    }
}
?>
```

Now, you replace "[[Type]]" by anything (integer, float, string, etc .. )
```php
<?php
public class Example{
    /**
     * [[Description]]
     * @param integer [$abc = ""] [[Description]]
     */
    protected function demo($abc = ""){
    }
}
?>
```
and place the cursor on the function and use again the shortcut (CTRL + ALT +D for me), this cancels what you wrote in all variables with default parameters (Type and Description).

**Comment by Wikunia** [comment]
Thanks for the issue! I hope this one fixes it. Please install from url. I'll register it, if everything works properly.

**Comment by adricorse** [comment]
It works! Thanks again ! :)
