### ISSUE TITLE
Comments -> full doc

### ISSUE THREAD

**Issue by adricorse** [Wikunia/brackets-FuncDocr#55]
Hello, 
Better than words, check this GIF :
![fixme](https://cloud.githubusercontent.com/assets/6782202/7770836/a9fd382e-0092-11e5-80b2-3d8bc21db1de.gif)

If you add "/\*" before a function, you have the full doc but you have the same reaction if "/\*" is before more one line.
Thanks ! :)

**Comment by Wikunia** [comment]
Do you think it would be better to provide the docs only directly before the function declaration.

**Comment by adricorse** [comment]
I think yes, if you want add comment anything before the function (as in the example above), your line of comments is removed.

**Comment by Wikunia** [comment]
Should be "solved" and not "solving" :D

**Comment by Wikunia** [comment]
It should work NOW :) 
Would be nice if you can check it using the "Install from URL" option! Thanks again

**Comment by adricorse** [comment]
Perfect ! I like it ! :)
Thanks again Wikunia ! Good luck for #56 ;)

**Comment by Wikunia** [comment]
Haha yeah that one is challenging. I'll have a deep look later today.
