### ISSUE TITLE
Comments in a function

### ISSUE THREAD

**Issue by adricorse** [Wikunia/brackets-FuncDocr#56]
Hello (again ;) ),
when you are in function, you can't use "/\*" to write a comment IF there is another function (defined or not by phpdoc) AND below it AND the comment is before a function, check it :
![oops](https://cloud.githubusercontent.com/assets/6782202/7772399/38c69928-009e-11e5-9804-0554d8d97515.gif)

**Comment by Wikunia** [comment]
That looks so strange :D 
Thanks for the issue. I really can't explain this at the moment :/

**Comment by Wikunia** [comment]
Would be nice if you can check `v0.8.23` (Install from URL)

**Comment by adricorse** [comment]
Yes, it works !
But, I forgot to say, instead of "$var = b();" you put "b();" like :
```php
<?php
function a(){
b();
}

function b(){
}
?>
```
there will be the same problem.. :(

**Comment by Wikunia** [comment]
Ahh that was in my mind but I forgot to check it. I'm sorry

**Comment by Wikunia** [comment]
Thanks for the issue and thanks for testing ;)
Can you try the newest `v.0.8.23` (no change in version :) ) 
Again via "Install from Url" Thanks!

**Comment by adricorse** [comment]
Nice ! :)
But ... (sorry ...)
Same issue with functions php, like :
```php
<?php
if(isset($a,$b)){
}
?>
```
result, with only using the shortcut (work fine with /* ):
```php
<?php
/**
 * [[Description]]
 * @param [[Type]] isset($a) [[Description]]
 */
if(isset($a)){
}
?>
```

**Comment by Wikunia** [comment]
I really hope it works now :D
thank you so much for all your issues and updates!

**Comment by adricorse** [comment]
You forgot "switch" ;) (but it also work with "/*" and shotcut)
```php
switch($far){
}
```

**Comment by Wikunia** [comment]
Damn :D

**Comment by Wikunia** [comment]
I've updated the list :)

**Comment by adricorse** [comment]
Good Job !
It works fine ! :)

**Comment by Wikunia** [comment]
Really that's it? No other bugs at the moment? :D 
Thanks for your work, I really appreciated it!

**Comment by adricorse** [comment]
Ahah, yeah, I haven't found other mistake :)
