### ISSUE TITLE
Conflict with TODO by Mikael Jorhult

### ISSUE THREAD

**Issue by sweakley23** [Wikunia/brackets-FuncDocr#58]
Todo entries won't display with this installed.

**Comment by Wikunia** [comment]
So this extension works but the to do ext stops working?

**Comment by sweakley23** [comment]
Correct. When you click on any of the todo's buttons like "FIX" nothing happens although occasionally the "TODO" list button would work temporarily. When I remove the FuncDocr extension, the TODO extension works again.

**Comment by Wikunia** [comment]
Okay, I will have a look later this week. I have a lot of uni stuff at the moment :/ I'll watch the other issue as well.

**Comment by Wikunia** [comment]
I think it works now. Would be great if you can update to the newest version and close this issue if everything works as expected.

**Comment by Klustre** [comment]
Works fine for me…

Brackets Release 1.5 build 1.5.0-16538 (release cf9cf4698)
FuncDocr 0.8.35
Todo 0.8.1
