### ISSUE TITLE
PHP - Comma as default value in parameter

### ISSUE THREAD

**Issue by cristidraghici** [Wikunia/brackets-FuncDocr#59]
When using FuncDocr on:
```
public function parse_csv ($csv_string, $delimiter = ",", $skip_empty_lines = true, $trim_fields = true)
```
the following is generated:
```
/**
 * [[Description]]
 * @param  [[Type]] $csv_string                        [[Description]]
 * @param  [[Type]] [$delimiter = "]                    [[Description]]
 * @param  [[Type]] "                                         [[Description]]
 * @param  [[Type]] [$skip_empty_lines = true] [[Description]]
 * @param  [[Type]] [$trim_fields = true]            [[Description]]
 * @return [[Type]] [[Description]]
 */
```

It is rarely that a comma is given as a default value, so it isn't an important or annoying bug. However, I am just letting you know it's there.

Kind regards!

**Comment by Wikunia** [comment]
Thanks for the issue! I'll try to have a look at the weekend, but it's quite full already :/

**Comment by Wikunia** [comment]
Can you install the newest version via url, please?
Thanks! 
Just close the issue if everything works well ;)

**Comment by cristidraghici** [comment]
It worked great! Thank you :+1:
