### ISSUE TITLE
Don't remove existing tags on update

### ISSUE THREAD

**Issue by Hirse** [Wikunia/brackets-FuncDocr#61]
The extension offers a wide range of tags as code hints which I sometimes use.
Unfortunately when I update the JsDoc of a function by using the keyboard shortcut all tags exept for the `@param` and `@returns` are removed again.

**Comment by Wikunia** [comment]
Oh damn! I'll have a look

**Comment by Wikunia** [comment]
@Hirse a test before registration would be nice. Thanks for the issue!

**Comment by Hirse** [comment]
Yes, looks good so far. Thanks for the quick fix.
