### ISSUE TITLE
Support for ES6 class methods

### ISSUE THREAD

**Issue by derwaldgeist** [Wikunia/brackets-FuncDocr#64]
At the moment, FuncDocr does not recognize ES6 constructors or class methods, which are not using the function keyword, like this:
```
class myClass {

   static classMethod(arg) {
   ...
   }

   constructor(arg) {
   ...
   }

   method(arg) {
   ...
   }

}
```

It would be nice if this would be implemented as ES6 is becoming more and more popular, as many JS frameworks switch to it (either using Babel/Traceur or using it directly).

The full ES6 class syntax is explained here: http://www.2ality.com/2015/02/es6-classes-final.html

**Comment by Wikunia** [comment]
the `constructor` function should work but I forgot the `static` thanks for the issue!

**Comment by Wikunia** [comment]
Would be great if you can test the newest version using "Install from URL"
Danke!

**Comment by derwaldgeist** [comment]
Thanks for this update. Unfortunately, I am not using Brackets anymore - I've switched to Atom in the meantime.
