### ISSUE TITLE
query

### ISSUE THREAD

**Issue by punitagarwal4** [Wikunia/brackets-FuncDocr#65]
Hello,
nice extension, i want to know that, after commenting on code by this extension, how can i create/generate documentation files(e.g. HTML documentation files)
is there any other software to do that ?

**Comment by Wikunia** [comment]
I don't use a software for it but you might wanna try:
https://jashkenas.github.io/docco/

**Comment by punitagarwal4** [comment]
Ok, can you please suggest, what should be used to make documentation, i am working as a developer, and it would be great if i can give good documentation to people who work under me and use functions and classes created by me. thanks for the help

**Comment by Wikunia** [comment]
I am not a specialist in that. There was the idea to help people while coding to get the documentation inside brackets so I started to build https://github.com/Wikunia/brackets-QuickDocsJS The next step was to make it easier to create those documentation therefore I've coded this one. Let's assume your coworkers are using Brackets as well they might wanna use my QuickDocsJS extension to have access to your docs directly inside Brackets without any other document. I like that way, cause it's fast, easy, airways there when you need it and definitely up to date.

**Comment by punitagarwal4** [comment]
thanks :)
