### ISSUE TITLE
Brackets freezes on certain code

### ISSUE THREAD

**Issue by vinegarZombie** [Wikunia/brackets-FuncDocr#68]
I have a small bit of code in my JS file such as:
```javascript
var staticVar = {
    lactatingCow : 16.5,
    lactatingSuckler : 12.5,
    dryCow : 10,
    silage : 1,
    meals : 1,
    procOfBody : 0.02
};
```
If I do ctrl+alt+D or /** brackets completely freezes , and the process has to be killed with task manager 
I am also not sure if this is related but if I want to enter a comment above the function ctrl+alt+D works fine but /** displays the proper code for a second and then removes itself.
This seams to be a issues since the latest update

**Comment by Wikunia** [comment]
The provided example is no function but yeah it should freeze but in my instance it doesn't.

**Comment by Wikunia** [comment]
Do you have any logs for the second part of the issue?

**Comment by vinegarZombie** [comment]
I also tried
````javascript
function staticVar = {
    lactatingCow : 16.5,
    lactatingSuckler : 12.5,
    dryCow : 10,
    silage : 1,
    meals : 1,
    procOfBody : 0.02
};
````
and it freeze as well . When I finally did a proper function it was all ok. 
I also notice that after I removed that chunk of code completely, the /** started to work properly. If you direct me to how to get the logs I can send them over

**Comment by Wikunia** [comment]
Oh yeah sure. `Debug -> Show Dev Tools` or on Linux,Windows (F12)

**Comment by Wikunia** [comment]
Okay which version of Brackets do you use?

**Comment by vinegarZombie** [comment]
Release 1.4 build 1.4.0-16380 (release 273804eb3) 
build timestamp: Mon Jul 27 2015 07:23:52 GMT+0100

**Comment by Wikunia** [comment]
Hmm that is strange it works on my machine with 1.5 and I checked your release as well. Hope there are some logs ;)

**Comment by Wikunia** [comment]
Does sth like:
```
$scope.getAllVersion=function(){

}

$scope.getAllVersion=function(asad){

}
```
work like in #67 ? Or does every function doesn't work properly?

**Comment by vinegarZombie** [comment]
I have lots of things going on in the console , don't really know which is relevant. I can see that I get
 sigKeys:  ["indentation", "parameters", "returns", "throws", "description", getUnique: function, getCol: function] whenever its successful, I also noticed , that it unfreeze after around 1.30 - 2min but nothing is really displayed in the console.
![screenshot 2015-10-15 16 39 04](https://cloud.githubusercontent.com/assets/8158118/10518910/5ba57d6c-735b-11e5-9c4e-06aa6e6eaf67.png) also sorry for not being more precise on the issues , as you can see I don't so this kind of reports often :)

**Comment by vinegarZombie** [comment]
`````
$scope.getAllVersion=function(){

}

$scope.getAllVersion=function(asad){

}
````
Both work fine
I get 
````
/**
 * [[Description]]
 */
````
and
````
/**
 * [[Description]]
 * @param {[[Type]]} asad [[Description]]
 */
````

**Comment by Wikunia** [comment]
It's fine and reminds me that I have to remove the normal logs next time :D
Can you move all your other extensions (you can go to the extension folder using: `Help -> Show Extension Folder`) to the folder disabled? (one folder above)

**Comment by vinegarZombie** [comment]
I just move everything from the user to disabled yes ?

**Comment by Wikunia** [comment]
Yeah but not my extension ;) Then you have to reload brackets and hopefully the error disappears. Then we can check your extensions ;)

**Comment by vinegarZombie** [comment]
![screenshot 2015-10-15 17 02 39](https://cloud.githubusercontent.com/assets/8158118/10519659/904f3456-735e-11e5-9bb2-656b03413711.png)
I moved everything other then FuncDocr to disabled , but it work the same around to min frozen and then its ok console is not showing nothing when that happens

**Comment by Wikunia** [comment]
Hmm and which version of FuncDocr worked for you?

**Comment by vinegarZombie** [comment]
![screenshot 2015-10-15 17 11 40](https://cloud.githubusercontent.com/assets/8158118/10519929/d98cfaf8-735f-11e5-9f65-9bc73375110e.png)
I am not sure which was the previous version , I normally keep everything up to date but I saw a update , so I clicked that was on Tuesday

**Comment by Wikunia** [comment]
Wow that doesn't make any sense to me :/ There was a really small change from v0.8.30 to v0.8.31

**Comment by vinegarZombie** [comment]
I must say it is bizarre. Maybe it was there before but I never commented that code , now I am not sure myself. Does it do anything on your side, or just doesn't generate the comment ?

**Comment by Wikunia** [comment]
```
var staticVar = {
    lactatingCow : 16.5,
    lactatingSuckler : 12.5,
    dryCow : 10,
    silage : 1,
    meals : 1,
    procOfBody : 0.02
};


function staticVar = {
    lactatingCow : 16.5,
    lactatingSuckler : 12.5,
    dryCow : 10,
    silage : 1,
    meals : 1,
    procOfBody : 0.02
};
```

Doesn't generate any comments but doesn't brake but well for me it's correct because it's not a function right?

**Comment by vinegarZombie** [comment]
Yes absolutely , they are not functions. To make things more interesting , I checked it on my home machine and nothing like this happens. It seams that its only a issues on my work laptop. Don't know how much difference it makes but my work laptop is win 8 and home machine win 7.

**Comment by Wikunia** [comment]
"Unfortunately" I have Linux ;) Okay I'll add some logs and then you can install from url. Stay tuned!

**Comment by Wikunia** [comment]
Thanks for testing!

**Comment by vinegarZombie** [comment]
No problems , thanks for a great plugin :)

**Comment by Wikunia** [comment]
Can you send me the new logs please :)

**Comment by vinegarZombie** [comment]
I think I have it. I made a small file 29 lines with some code , and I couldn't see the code freezing. I did notice that the 'code:' section displays the entire file so 29 lines of code. The previous code where the freezing happens is over 300 lines and 'that' code is on the top of the file so the entire 300 lines are being parsed 
![screenshot 2015-10-16 09 46 33](https://cloud.githubusercontent.com/assets/8158118/10537966/3826b21a-73ed-11e5-8989-07e4918e8903.png)

**Comment by Wikunia** [comment]
Oh okay, thanks. Now I can reproduce the error, at the moment I have no idea why this happens, but yeah I'll work on it!

**Comment by Wikunia** [comment]
I hope I have good news for you @vinegarZombie  ;) Would be great if you can install the bugfix via url. 
Just close the issue, if everything works, then I'll register the new version. Thanks for your issue and help again!

**Comment by vinegarZombie** [comment]
@Wikunia I can confirm that it does fix the problem :) just in the console I saw that brackets isn't fully happy with  the regexp , but nothing bad is happening.
![screenshot 2015-10-16 12 08 05](https://cloud.githubusercontent.com/assets/8158118/10540346/083babca-73ff-11e5-96d7-3ba61a210b06.png)

**Comment by Wikunia** [comment]
Well it's just a long long regexp which I printed out :D I'm so sorry that I use regexes for this kind of stuff, but there is no good parser which supports JS and PHP :(

**Comment by vinegarZombie** [comment]
Nah its nothing, As long as it works :) :+1:
