### ISSUE TITLE
Support exported functions

### ISSUE THREAD

**Issue by stowball** [Wikunia/brackets-FuncDocr#70]
FuncDocr doesn't work on `export`ed functions such as the code below, unless you first remove the `export default`. 

```js
export default function getJSON(url, onSuccess, onError) {
}
```

**Comment by Wikunia** [comment]
Hi @stowball can you give me some more information about this structure?
Never had function declarations like this one, so is it only working with `export default` or is possible to just use `export` and is it possible to use `private export default function` or some stuff like this?
I'm sorry at the moment this extension uses regexes and not a parser (see more details in the readme) :/

**Comment by stowball** [comment]
It's the syntax for using ES6/Require modules http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by Wikunia** [comment]
Would be great if you can test this via url. Then I will register it afterwards!
Thanks for the issue!

**Comment by stowball** [comment]
Love your work
