### ISSUE TITLE
Add @author with array of authors, please

### ISSUE THREAD

**Issue by nguyentuandat** [Wikunia/brackets-FuncDocr#71]
Can you add @author with array of authors name like 'John', 'Oliver',... and user can choose one when use this?

**Comment by Wikunia** [comment]
You mean an array inside the settings panel?

**Comment by nguyentuandat** [comment]
yeah :+1:

**Comment by Wikunia** [comment]
The normal behavior is to include only you as the author because therefore you can add your name to the function.

**Comment by nguyentuandat** [comment]
So, how can it auto add @author when i type /** and Enter?

**Comment by Wikunia** [comment]
Interesting idea, but that has nothing to do with an array of authors, right?

**Comment by nguyentuandat** [comment]
That right. But if it can auto generate @author and "Author name", it'll awesome.
Ex: 
@author:  Wikunia

Thanks for your supported :)

**Comment by Wikunia** [comment]
I'll work on that in the next days. Thanks for the idea!

**Comment by Wikunia** [comment]
Hi @nguyentuandat would be great if you can check the new version ;)
(Install from Url)
I'll register the new version if everything works fine. Thanks again!

**Comment by nguyentuandat** [comment]
Thank you so much. It work. But in case the user turn off auto add @author tag, type @autho... enter :)
![Bug](http://oorts.info/FuncDocr_bug.png)
Here is @author [[Author]] but on setting panel is [[Name]]

**Comment by Wikunia** [comment]
Unfortunately you need to use `Ctrl-Space` to see the hint (sometimes). Don't know why this happens. I clarified the term inside the settings panel.
