### ISSUE TITLE
Lowercase types in JS

### ISSUE THREAD

**Issue by Hirse** [Wikunia/brackets-FuncDocr#72]
Currently the type hints in JS show all options as Titlecase.
Base on the [JSDoc type documentation](http://usejsdoc.org/tags-type.html), I would think it would be more appropriate to have the primitive types as all lowercase.
That means 
"number", "string", "boolean", "object", and "function"

**Comment by Wikunia** [comment]
Thanks @Hirse . You can create a PR, if you want or I will implement it the next days!
