### ISSUE TITLE
/* triggers a JSDoc comment block instead of /**

### ISSUE THREAD

**Issue by arctwelve** [Wikunia/brackets-FuncDocr#79]
The extension uses  `/** + Enter` to trigger the comment block at the beginning of a function. 

That works, but it will also recognize `/* + Enter`  (one asterisk). That prevents the user from adding general comments instead of JSDoc ones.

**Comment by arctwelve** [comment]
@Wikunia Wow, awesome. That was fast!

**Comment by Wikunia** [comment]
well and easy :D

**Comment by arctwelve** [comment]
Just thinking...maybe instead of `/* + enter` doing nothing,  `/* + enter` created a general comment block. So `/* + enter` creates:
```javascript
/*
 * [[Description]]
 */
```
with `[[Description]]` highlighted to edit. General comments would only have `[[Description]]` and the shortcut would work anywhere inside a js file (i.e., inside or outside a function). 

The extension would now completely take care of all block comments: JSDoc and general.

**Comment by Wikunia** [comment]
There is an extension for general comments. 
https://github.com/peterflynn/reasonable-comments
