### ISSUE TITLE
@private tag

### ISSUE THREAD

**Issue by Hirse** [Wikunia/brackets-FuncDocr#82]
Could you add support for the `@private` tag?

1. Format existing JSDoc with has a `@private` tag.
2. Add a `@private` tag if the function name starts with an underscore.

**Comment by Wikunia** [comment]
I am not using Brackets that often anymore so it will take a bit longer. But I will work on it. Thanks for the request.

**Comment by ekatzenstein** [comment]
@Wikunia , what are you using these days instead of Brackets?

**Comment by Wikunia** [comment]
Mostly Webstorm which isn't open source, unfortunately.

**Comment by Wikunia** [comment]
Again thanks for your issue! Would be great if you can update to the new version.
The version isn't registered yet, but you can easily update using `Install from URL`.
If everything works fine, I'll register the new version asap. 
Have an nice day!

**Comment by Hirse** [comment]
For a function like `Object.prototype.get = function` I am getting the following error: 

> Uncaught TypeError: Cannot read property 'charAt' of undefined 
in [main.js line 601](https://github.com/Wikunia/brackets-FuncDocr/blob/master/main.js#L601) because `signatureObj.funcName` is undefined.

**Comment by Wikunia** [comment]
I'm sorry, I missed something... Hope it works now ;)

**Comment by Hirse** [comment]
Yes, looks good now. Thanks.
