### ISSUE TITLE
Support generator function auto-completition

### ISSUE THREAD

**Issue by petetnt** [Wikunia/brackets-FuncDocr#84]
> The function* declaration (function keyword followed by an asterisk) defines a generator function, which returns a Generator object.

Basically all that needs to be done is to accept asterixes after the "function" keyword.

Current behavior: 
``` js
// Auto complete works when typing /** + Enter:
function foo() {

}

// Doesn't work:
function* foo() {

}

```

REF: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*

Thanks once again for this great extension!

**Comment by Wikunia** [comment]
Would be great if you can install from url and test it a bit and then close this issue. Afterwards I will register the new version!
Thanks for the request. Have a nice day!

**Comment by petetnt** [comment]
Works great, thanks @Wikunia! :+1:
