### ISSUE TITLE
Spurious logs

### ISSUE THREAD

**Issue by ficristo** [Wikunia/brackets-FuncDocr#88]
There are some spurious log on the console:
`Uncaught TypeError: tagDef.replace is not a function`
`throw throws`
and a regex

**Comment by Wikunia** [comment]
What do you do to get the `Uncaught TypeError: tagDef.replace is not a function` error?
I don't see that one. Thanks for the issue.

**Comment by ficristo** [comment]
It seems is related to the `@constructor` js annotation. Using the `tab` keyword to go to `{[[Type]]}` it throws the exception above.
```js
/**
 * Description
 * @constructor
 * @param {[[Type]]} foo [[Description]]
 */
function test(foo) {
}
```

**Comment by Wikunia** [comment]
Should work now! Thanks again :)

**Comment by ficristo** [comment]
In the last commit some `console.log` went in the tree.
