### ISSUE TITLE
Not working in Brackets  1.9

### ISSUE THREAD

**Issue by loup-brun** [Wikunia/brackets-FuncDocr#90]
Typing `/**` + enter does not work. Accessing the command through the menu (Edit > funcdocr) does not work either, nor does its associated hotkey.

No errors outputed in Brackets console.

Issue occurs both in js and php files.

Using `Brackets version 1.9 edition 1.9.0-17312 (release 189f6d39a)`

**Comment by Wikunia** [comment]
Sorry for the late reply. I'm currently on vacation and will have a look in about two weeks.

**Comment by Wikunia** [comment]
Do you have any console logs for it (F12 or Debug -> Show Developer Tools) ?
It works for me on 1.10.

**Comment by loup-brun** [comment]
Well I've updated to Brackets 1.10 and it works! Thanks!
